export const nearbyPlaces = [
  {
    id: "1",
    name: "The Mills – Baner",
    distance: "5.8 km",
    address: "Balasaheb 307 Rd, Tripti Marg",
    icon: "clock", 
  },
  {
    id: "2",
    name: "Nirvana Apartments",
    distance: "3.1 km",
    address: "Amanora Park Town, Hadapsar, Infron...",
    icon: "home",
  },
  {
    id: "3",
    name: "Studio Do-Undo",
    distance: "4.5 km",
    address: "Shankar Tupe Marg, Malwadi",
    icon: "work",
  },
  {
    id: "4",
    name: "Oasis Heights",
    distance: "6.2 km",
    address: "Kharadi, Near Eon IT Park",
    icon: "location",
  },
  {
    id: "5",
    name: "Tranquil Meadows",
    distance: "7.4 km",
    address: "Baner, Adjacent to Balewadi Stadium",
    icon: "location",
  },
  {
    id: "6",
    name: "Serenity Villas",
    distance: "8.9 km",
    address: "Viman Nagar, Close to Phoenix Market...",
    icon: "location",
  },
  {
    id: "7",
    name: "Harmony Residences",
    distance: "2.4 km",
    address: "Kothrud, Near MIT College",
    icon: "location",
  },
    {
    id: "8",
    name: "Tranquil Meadows",
    distance: "7.4 km",
    address: "Baner, Adjacent to Balewadi Stadium",
    icon: "location",
  },
  {
    id: "9",
    name: "Serenity Villas",
    distance: "8.9 km",
    address: "Viman Nagar, Close to Phoenix Market...",
    icon: "location",
  },
  {
    id: "10",
    name: "Harmony Residences",
    distance: "2.4 km",
    address: "Kothrud, Near MIT College",
    icon: "location",
  },
   {
    id: "11",
    name: "Harmony Residences",
    distance: "2.4 km",
    address: "Kothrud, Near MIT College",
    icon: "location",
  },
];
